# Generated by Django 2.0.3 on 2018-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataman', '0003_filecodelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
    ]
