# Generated by Django 2.0.3 on 2018-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataman', '0005_datachank'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachank',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
