# Generated by Django 2.2.1 on 2019-06-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataman', '0007_auto_20180511_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datachank',
            name='user',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
