# Generated by Django 2.0.3 on 2018-03-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20180325_0623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
