# Generated by Django 2.0.3 on 2018-03-24 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeelement',
            name='user',
        ),
        migrations.AddField(
            model_name='codeelement',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
