# Generated by Django 2.0.3 on 2018-03-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeman', '0002_auto_20180324_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeelement',
            name='user',
        ),
        migrations.AddField(
            model_name='codeelement',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
