# Generated by Django 2.2.1 on 2019-06-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeman', '0004_codemeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeelement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='codemeta',
            name='user',
        ),
    ]
